openapi: 3.0.3
info:
  title: Youtube Video Sharing API
  version: 0.0.1
paths:
  /api/users/info:
      post:
        security:
          - bearerAuth: []
        tags:
          - users
        responses:
          '200':
            description: Successful
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UsersInfoResponse'
          '400':
            description: Bad Request
  /api/users/registry:
    post:
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad Request
  /api/users/login:
    post:
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersRequestBody'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
components:
  schemas:
    UsersEntity:
      type: object
      properties:
        email:
          type: string
    UsersInfoResponse:
      type: object
      properties:
        message:
          type: string
          example: Get Info Successfully
        data:
          $ref: '#/components/schemas/UsersEntity'
    UsersRequestBody:
      type: object
      properties:
        email:
          type: string
          example: string@gmail.com
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: Registry Successfully
    LoginResponse:
      type: object
      properties:
        message:
          type: string
          example: Login Successfully
        data:
          type: object
          properties:
            token:
              type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
